"""
Definições canônicas de portas Down Plant para o cômodo OWNER_INTENT.
"""
PORT_OWNER_INTENT_INGEST = "HANGAR_V1/AZ000_GOVERNANCA_SOBERANIA/OWNER_INTENT/INTENT_INGESTION:P-OWNER-INTENT-INGEST-01"
PORT_INTENT_NORMALIZATION = "HANGAR_V1/AZ000_GOVERNANCA_SOBERANIA/OWNER_INTENT/INTENT_INGESTION:P-INTENT-NORMALIZATION-01"
PORT_INTENT_VALIDATION = "HANGAR_V1/AZ000_GOVERNANCA_SOBERANIA/OWNER_INTENT/SEALED_CONTRACT_EMITTER:P-INTENT-VALIDATION-01"
PORT_INTENT_SEAL = "HANGAR_V1/AZ000_GOVERNANCA_SOBERANIA/OWNER_INTENT/SEALED_CONTRACT_EMITTER:P-INTENT-SEAL-01"
PORT_INTENT_HANDOFF_N01 = "HANGAR_V1/AZ000_GOVERNANCA_SOBERANIA/OWNER_INTENT/SEALED_CONTRACT_EMITTER:P-INTENT-HANDOFF-N01-01"
PORT_PLANNER_N01_RECEIVE = "MOCK-TERRAIN/Hangar/CharPlanner/Core:P-PLAN-01"
